name: Render Test

on:
    workflow_dispatch:
        inputs:
            jsreport_hostname:
                description: 'The hostname/ip that points to where jsreport is running'
                default: 'localhost'
                required: false
                type: string
            
            http_server_hostname:
                description: 'The hostname/ip that points to the web server that hosts the css file'
                default: 'localhost'
                required: false
                type: string


jobs:
    test:
        runs-on: ubuntu-latest
        container: 
            image: node:20-alpine
            options: --network-alias host
        services:
            jsreport:
                image: jsreport/jsreport:4.5.0-full
                env:
                    extensions_chromePdf_launchOptions_args: --no-sandbox
        steps:
            - name: whoami
              run: whoami

            - name: Set System locale
              run: |
                locale-gen en_GB.UTF-8
                update-locale LANG=en_GB.UTF-8

            - name: install stuff
              run: apt-get update && apt-get install -y ghostscript libfontconfig1

            - name: check pwsh
              shell: pwsh
              run: Get-Location

            - uses: actions/checkout@v4

            - name: sleep
              run: sleep 10s

            - name: exec
              env:
                JSREPORT_HOSTNAME: ${{ inputs.jsreport_hostname }}
                HTTP_SERVER_HOSTNAME: ${{ inputs.http_server_hostname }}
              run: node ./exec.mjs
            
            - name: Save result
              uses: actions/upload-artifact@v3
              with:
                name: result.pdf
                path: result.pdf
                retention-days: 5